server:
  port: 10001


logging:
  level:
    root: INFO
    io.swagger.models.parameters.AbstractSerializableParameter: error


spring:
  freemarker:
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  datasource:
    name: db_xydemo
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.196.111:3306/db_xydemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 20
      maxWait: 5000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      logAbandoned: true
      removeAbandoned: true
      removeAbandonedTimeout: 180
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
mybatis:
  type-aliases-package: com.xydemo.model
  mapper-locations: classpath*:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mapper:
  not-empty: false
  style: camelhumpandlowercase
  before: true



swagger2-api:
  enable-swagger: true
  title: "Api文档"
  description: "demo Api文档"
  version: 1.0
  name: "管理后台"
  url: "http://localhost:10001/docs.html"
  email: "674806334@qq.com"
  termsOfServiceUrl: "NO terms of service"
  license: "DEMO Public License 1.0"
  licenseUrl: "http://localhost:10001/docs.html"

