

server:
  port: 8082

spring:
  application:
    name: xydemo-springcloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.172:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.101:8080
      eager: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

#启动熔断器
feign:
  sentinel:
    enabled: true

