
server:
  port: 7777

spring:
  application:
    name: xydemo-dubbo-sentinel-client
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.0.101:8080
      eager: true


nacos:
  service-address: 192.168.0.172
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}


#启动熔断器
feign:
  sentinel:
    enabled: true

