
server:
  port: 8081

spring:
  application:
    name: xydemo-springcloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.172:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
