
server:
  port: 7777

spring:
  application:
    name: xydemo-dubbo-client

nacos:
  service-address: 10.11.41.65
  port: 8848
dubbo:
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}











