server:
  port: 8888
spring:
  application:
    name: xydemo-dubbo-service

nacos:
  service-address: 192.168.0.172
  port: 8848
dubbo:
  application:
    name: xydemo-dubbo-service
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}
  protocols:
    dubbo:
      name: dubbo
      port: 20001
      server: netty
    rest:
      name: rest
      port: 8088
      server: jetty
  scan:
    base-packages: com.xydemo.service.impl









